/**
 * Datos de demostración que simulan ~20 trenes Renfe activos en la red
 * española. Posiciones GPS reales a lo largo de los corredores principales,
 * retrasos variados, material rodante real.
 *
 * Se usa cuando DEMO_MODE=true o cuando el upstream de Renfe no es accesible.
 */

import type { LiveTrain } from "../types.js";

function iso(): string {
  return new Date().toISOString();
}

export function getDemoTrains(): LiveTrain[] {
  const now = iso();
  return [
    {
      code: "03072",
      service: "AVE",
      operator: "RENFE",
      origin: "Madrid-Puerta de Atocha",
      destination: "Barcelona-Sants",
      lat: 40.452,
      lon: -1.856,
      heading: 58,
      speedKmh: 302,
      delayMinutes: 0,
      previousStop: { code: "60000", name: "Madrid-Puerta de Atocha", scheduled: "09:00", estimated: "09:00", departed: true },
      nextStop: { code: "79300", name: "Zaragoza-Delicias", scheduled: "10:15", estimated: "10:15", departed: false },
      rollingStock: "S-103",
      updatedAt: now,
    },
    {
      code: "04154",
      service: "AVE",
      operator: "RENFE",
      origin: "Madrid-Puerta de Atocha",
      destination: "Sevilla Santa Justa",
      lat: 38.85,
      lon: -3.92,
      heading: 195,
      speedKmh: 298,
      delayMinutes: 3,
      previousStop: { code: "60000", name: "Madrid-Puerta de Atocha", scheduled: "08:30", estimated: "08:30", departed: true },
      nextStop: { code: "51003", name: "Córdoba Central", scheduled: "10:15", estimated: "10:18", departed: false },
      rollingStock: "S-102",
      updatedAt: now,
    },
    {
      code: "02130",
      service: "AVLO",
      operator: "RENFE",
      origin: "Madrid-Puerta de Atocha",
      destination: "Barcelona-Sants",
      lat: 41.21,
      lon: -0.32,
      heading: 72,
      speedKmh: 290,
      delayMinutes: 0,
      previousStop: { code: "79300", name: "Zaragoza-Delicias", scheduled: "08:50", estimated: "08:50", departed: true },
      nextStop: { code: "78400", name: "Lleida-Pirineus", scheduled: "09:40", estimated: "09:40", departed: false },
      rollingStock: "S-106",
      updatedAt: now,
    },
    {
      code: "04260",
      service: "AVE",
      operator: "RENFE",
      origin: "Sevilla Santa Justa",
      destination: "Madrid-Puerta de Atocha",
      lat: 38.25,
      lon: -4.92,
      heading: 15,
      speedKmh: 285,
      delayMinutes: 7,
      previousStop: { code: "51003", name: "Sevilla Santa Justa", scheduled: "07:45", estimated: "07:45", departed: true },
      nextStop: { code: "51003", name: "Córdoba Central", scheduled: "08:30", estimated: "08:37", departed: false },
      rollingStock: "S-100",
      updatedAt: now,
    },
    {
      code: "03192",
      service: "ALVIA",
      operator: "RENFE",
      origin: "Madrid-Chamartín",
      destination: "Gijón-Jovellanos",
      lat: 42.45,
      lon: -5.1,
      heading: 340,
      speedKmh: 180,
      delayMinutes: 12,
      previousStop: { code: "15206", name: "León", scheduled: "11:30", estimated: "11:40", departed: true },
      nextStop: { code: "15402", name: "Oviedo", scheduled: "12:50", estimated: "13:02", departed: false },
      rollingStock: "S-130",
      updatedAt: now,
    },
    {
      code: "00242",
      service: "ALVIA",
      operator: "RENFE",
      origin: "Barcelona-Sants",
      destination: "Bilbao-Abando",
      lat: 42.75,
      lon: -1.65,
      heading: 290,
      speedKmh: 185,
      delayMinutes: 5,
      previousStop: { code: "79300", name: "Zaragoza-Delicias", scheduled: "10:00", estimated: "10:05", departed: true },
      nextStop: { code: "11600", name: "Pamplona/Iruña", scheduled: "11:20", estimated: "11:25", departed: false },
      rollingStock: "S-120",
      updatedAt: now,
    },
    {
      code: "05470",
      service: "AVE",
      operator: "RENFE",
      origin: "Madrid-Puerta de Atocha",
      destination: "Málaga María Zambrano",
      lat: 37.62,
      lon: -4.47,
      heading: 205,
      speedKmh: 295,
      delayMinutes: 0,
      previousStop: { code: "51003", name: "Córdoba Central", scheduled: "10:10", estimated: "10:10", departed: true },
      nextStop: { code: "31402", name: "Málaga María Zambrano", scheduled: "11:05", estimated: "11:05", departed: false },
      rollingStock: "S-103",
      updatedAt: now,
    },
    {
      code: "05123",
      service: "AVE",
      operator: "RENFE",
      origin: "Madrid-Puerta de Atocha",
      destination: "Valencia Joaquín Sorolla",
      lat: 39.45,
      lon: -1.35,
      heading: 130,
      speedKmh: 285,
      delayMinutes: 0,
      previousStop: { code: "60000", name: "Madrid-Puerta de Atocha", scheduled: "09:30", estimated: "09:30", departed: true },
      nextStop: { code: "65000", name: "Valencia Joaquín Sorolla", scheduled: "11:10", estimated: "11:10", departed: false },
      rollingStock: "S-112",
      updatedAt: now,
    },
    {
      code: "04092",
      service: "EUROMED",
      operator: "RENFE",
      origin: "Barcelona-Sants",
      destination: "Alicante Terminal",
      lat: 39.95,
      lon: -0.02,
      heading: 210,
      speedKmh: 195,
      delayMinutes: 2,
      previousStop: { code: "64200", name: "Castellón de la Plana", scheduled: "10:30", estimated: "10:32", departed: true },
      nextStop: { code: "65000", name: "Valencia Joaquín Sorolla", scheduled: "11:15", estimated: "11:17", departed: false },
      rollingStock: "S-101",
      updatedAt: now,
    },
    {
      code: "18204",
      service: "MD",
      operator: "RENFE",
      origin: "Sevilla Santa Justa",
      destination: "Huelva Terminal",
      lat: 37.35,
      lon: -6.23,
      heading: 255,
      speedKmh: 120,
      delayMinutes: 0,
      previousStop: { code: "51003", name: "Sevilla Santa Justa", scheduled: "08:45", estimated: "08:45", departed: true },
      nextStop: { code: "37100", name: "Huelva Terminal", scheduled: "10:15", estimated: "10:15", departed: false },
      rollingStock: "S-599",
      updatedAt: now,
    },
    {
      code: "13052",
      service: "TALGO",
      operator: "RENFE",
      origin: "Madrid-Chamartín",
      destination: "A Coruña San Cristóbal",
      lat: 41.63,
      lon: -7.55,
      heading: 285,
      speedKmh: 160,
      delayMinutes: 18,
      previousStop: { code: "20200", name: "Ourense-Empalme", scheduled: "12:00", estimated: "12:15", departed: true },
      nextStop: { code: "21100", name: "Santiago de Compostela", scheduled: "13:20", estimated: "13:38", departed: false },
      rollingStock: "T-730",
      updatedAt: now,
    },
    {
      code: "03940",
      service: "AVE",
      operator: "RENFE",
      origin: "Barcelona-Sants",
      destination: "Madrid-Puerta de Atocha",
      lat: 41.42,
      lon: 1.12,
      heading: 240,
      speedKmh: 300,
      delayMinutes: 0,
      previousStop: { code: "71801", name: "Barcelona-Sants", scheduled: "10:00", estimated: "10:00", departed: true },
      nextStop: { code: "79206", name: "Camp de Tarragona", scheduled: "10:35", estimated: "10:35", departed: false },
      rollingStock: "S-103",
      updatedAt: now,
    },
    {
      code: "02074",
      service: "AVLO",
      operator: "RENFE",
      origin: "Madrid-Puerta de Atocha",
      destination: "Sevilla Santa Justa",
      lat: 39.38,
      lon: -3.68,
      heading: 200,
      speedKmh: 295,
      delayMinutes: 0,
      previousStop: { code: "60000", name: "Madrid-Puerta de Atocha", scheduled: "10:15", estimated: "10:15", departed: true },
      nextStop: { code: "51003", name: "Córdoba Central", scheduled: "12:00", estimated: "12:00", departed: false },
      rollingStock: "S-106",
      updatedAt: now,
    },
    {
      code: "17054",
      service: "INTERCITY",
      operator: "RENFE",
      origin: "Barcelona-Sants",
      destination: "Vigo-Guixar",
      lat: 42.17,
      lon: -3.72,
      heading: 270,
      speedKmh: 155,
      delayMinutes: 25,
      previousStop: { code: "11300", name: "Burgos Rosa de Lima", scheduled: "11:00", estimated: "11:20", departed: true },
      nextStop: { code: "15206", name: "León", scheduled: "12:30", estimated: "12:55", departed: false },
      rollingStock: "S-449",
      updatedAt: now,
    },
    {
      code: "03560",
      service: "AVE",
      operator: "RENFE",
      origin: "Málaga María Zambrano",
      destination: "Madrid-Puerta de Atocha",
      lat: 37.95,
      lon: -4.15,
      heading: 30,
      speedKmh: 300,
      delayMinutes: 0,
      previousStop: { code: "31402", name: "Málaga María Zambrano", scheduled: "08:15", estimated: "08:15", departed: true },
      nextStop: { code: "51003", name: "Córdoba Central", scheduled: "09:10", estimated: "09:10", departed: false },
      rollingStock: "S-102",
      updatedAt: now,
    },
    {
      code: "04810",
      service: "ALVIA",
      operator: "RENFE",
      origin: "Madrid-Chamartín",
      destination: "Santander",
      lat: 42.95,
      lon: -3.78,
      heading: 350,
      speedKmh: 165,
      delayMinutes: 8,
      previousStop: { code: "11300", name: "Burgos Rosa de Lima", scheduled: "12:00", estimated: "12:06", departed: true },
      nextStop: { code: "13200", name: "Santander", scheduled: "13:30", estimated: "13:38", departed: false },
      rollingStock: "S-130",
      updatedAt: now,
    },
    {
      code: "09442",
      service: "MD",
      operator: "RENFE",
      origin: "Valencia Joaquín Sorolla",
      destination: "Alicante Terminal",
      lat: 38.82,
      lon: -0.55,
      heading: 195,
      speedKmh: 140,
      delayMinutes: 0,
      previousStop: { code: "65000", name: "Valencia Joaquín Sorolla", scheduled: "09:45", estimated: "09:45", departed: true },
      nextStop: { code: "66200", name: "Alicante Terminal", scheduled: "11:30", estimated: "11:30", departed: false },
      rollingStock: "S-449",
      updatedAt: now,
    },
    {
      code: "14072",
      service: "REGIONAL",
      operator: "RENFE",
      origin: "Zaragoza-Delicias",
      destination: "Huesca",
      lat: 42.02,
      lon: -0.56,
      heading: 350,
      speedKmh: 100,
      delayMinutes: 4,
      previousStop: { code: "79300", name: "Zaragoza-Delicias", scheduled: "10:10", estimated: "10:10", departed: true },
      nextStop: { code: "74200", name: "Huesca", scheduled: "11:10", estimated: "11:14", departed: false },
      rollingStock: "S-599",
      updatedAt: now,
    },
  ];
}
